package com.sanjaybhat.filmrecommend.model

const val TMDB_IMG_BASE = "https://image.tmdb.org/t/p/"

object PosterData {
    val posters: Map<String, String> = mapOf(
        "300" to "/h7Lcio0c9ohxPhSZg42eTlKIVVY.jpg",
        "A Beautiful Mind" to "/rEIg5yJdNOt9fmX4P8gU9LeNoTQ.jpg",
        "Aladdin" to "/eLFfl7vS8dkeG1hKp5mwbm37V83.jpg",
        "Alien" to "/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
        "Aliens" to "/r1x5JGpyqZU8PYhbs4UcrO1Xb6x.jpg",
        "American History X" to "/x2drgoXYZ8484lqyDj7L1CEVR4T.jpg",
        "Apollo 13" to "/tVeKscCm2fY1xDXZk8PgnZ87h9S.jpg",
        "Avatar" to "/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg",
        "Back to the Future" to "/vN5B5WgYscRGcQpVhHl6p9DDTP0.jpg",
        "Batman Begins" to "/sPX89Td70IDDjVr85jdSBb4rWGr.jpg",
        "Beauty and the Beast" to "/hUJ0UvQ5tgE2Z9WpfuduVSdiCiU.jpg",
        "Blade Runner" to "/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg",
        "Brave" to "/1XAuDtMWpL0sYSFK0R6EZate2Ux.jpg",
        "Braveheart" to "/or1gBugydmjToAEq7OZY0owwFk.jpg",
        "Captain America: The Winter Soldier" to "/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg",
        "Casino" to "/lMrxYKKhd4lqRzwUHAy5gcx9PSO.jpg",
        "Cast Away" to "/7lLJgKnAicAcR5UEuo8xhSMj18w.jpg",
        "Catch Me If You Can" to "/ctjEj2xM32OvBXCq8zAdK3ZrsAj.jpg",
        "Close Encounters of the Third Kind" to "/yaPx3cK9zGFX3SbcKwxWM1QIbUh.jpg",
        "Die Hard" to "/7Bjd8kfmDSOzpmhySpEhkUyK2oH.jpg",
        "Divergent" to "/aNh4Q3iuPKDMPi2SL7GgOpiLukX.jpg",
        "Django Unchained" to "/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
        "Dredd" to "/cfSnKn8NDU3m8UxihjVcYprA0Aq.jpg",
        "E.T. the Extra-Terrestrial" to "/an0nD6uq6byfxXCfk6lQBzdL2J1.jpg",
        "Edge of Tomorrow" to "/nBM9MMa2WCwvMG4IJ3eiGUdbPe6.jpg",
        "Ender's Game" to "/pVcRI5YKnkkgaAD876jBeKb189d.jpg",
        "Fight Club" to "/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg",
        "Finding Nemo" to "/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg",
        "Forrest Gump" to "/Cw4hIUIAmSYfK9QfaUW5igp9La.jpg",
        "Frozen" to "/itAKcobTYGpYT8Phwjd8c9hleTo.jpg",
        "Gangs of New York" to "/lemqKtcCuAano5aqrzxYiKC8kkn.jpg",
        "Gladiator" to "/wN2xWp1eIwCKOD0BHTcErTBv1Uq.jpg",
        "Gone Girl" to "/ts996lKsxvjkO2yFG0ht4qAicO.jpg",
        "Goodfellas" to "/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg",
        "Gravity" to "/kZ2nZw8D681aphje8NJi8EfbL1U.jpg",
        "Guardians of the Galaxy" to "/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
        "Harry Potter and the Philosopher's Stone" to "/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
        "Heat" to "/umSVjVdbVwtx5ryCA2QXL44Durm.jpg",
        "Inception" to "/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg",
        "Indiana Jones and the Last Crusade" to "/sizg1AU8f8JDZX4QIgE4pjUMBvx.jpg",
        "Inglourious Basterds" to "/aupnPtagH9JVBuMrGEanf4iqXEQ.jpg",
        "Interstellar" to "/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg",
        "Iron Man" to "/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
        "Jaws" to "/lxM6kqilAdpdhqUl2biYp5frUxE.jpg",
        "John Carter" to "/lCxz1Yus07QCQQCb6I0Dr3Lmqpx.jpg",
        "Jurassic Park" to "/63viWuPfYQjRYLSZSZNq7dglJP5.jpg",
        "Jurassic World" to "/1RICxzeoNCAO5NpcRMIgg1XT6fm.jpg",
        "Kill Bill: Vol. 1" to "/v7TaX8kXMXs5yFFGR41guUDNcnB.jpg",
        "Kingdom of Heaven" to "/rNaBe4TwbMef71sgscqabpGKsxh.jpg",
        "Life of Pi" to "/iLgRu4hhSr6V1uManX6ukDriiSc.jpg",
        "Mad Max: Fury Road" to "/ulcAi4dKpAjHwYGS08vNyx9H6I9.jpg",
        "Memento" to "/nzlv62aC0octS5AklAiWpXLX9Z0.jpg",
        "Minority Report" to "/qtgFcnwh9dAFLocsDk2ySDVS8UF.jpg",
        "Moana" to "/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg",
        "Monsters, Inc." to "/wFSpyMsp7H0ttERbxY7Trlv8xry.jpg",
        "Mulan" to "/jAbexAtB0aSfP5Ay4TpWHARyVnG.jpg",
        "National Treasure" to "/pxL6E4GBOPUG6CdkO9cUQN5VMwI.jpg",
        "Pacific Rim" to "/8wo4eN8dWKaKlxhSvBz19uvj8gA.jpg",
        "Percy Jackson & the Olympians: The Lightning Thief" to "/brzpTyZ5bnM7s53C1KSk1TmrMO6.jpg",
        "Pirates of the Caribbean: The Curse of the Black Pearl" to "/poHwCZeWzJCShH7tOjg8RIoyjcw.jpg",
        "Predator" to "/pHpq9yNUIo6aDoCXEBzjSolywgz.jpg",
        "Pulp Fiction" to "/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
        "Ratatouille" to "/t3vaWRPSf6WjDSamIkKDs1iQWna.jpg",
        "Reservoir Dogs" to "/xi8Iu6qyTfyZVDVy60raIOYJJmk.jpg",
        "Revolutionary Road" to "/cvkD3yiVXLg3as8EAG3LaTycONQ.jpg",
        "Robin Hood" to "/92Tsfx7SFafOqWsotvrlJbHyehd.jpg",
        "RoboCop" to "/hHtOgGb3NihlyRATHlKPaFApbrd.jpg",
        "Saving Private Ryan" to "/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg",
        "Scarface" to "/iQ5ztdjvteGeboxtmRdXEChJOHh.jpg",
        "Schindler's List" to "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
        "Se7en" to "/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg",
        "Shutter Island" to "/nrmXQ0zcZUL8jFLrakWc90IR8z9.jpg",
        "Spider-Man" to "/iPOn6DinuVyLY17YM9mKuPofV08.jpg",
        "Star Trek Into Darkness" to "/Aim3kVNh1MPIxPEFeJrl9e9Uf1a.jpg",
        "Star Wars" to "/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
        "Tangled" to "/ym7Kst6a4uodryxqbGOxmewF235.jpg",
        "Tarzan" to "/bTvHlcqiOjGa3lFtbrTLTM3zasY.jpg",
        "Terminator 2: Judgment Day" to "/jFTVD4XoWQTcg7wdyJKa8PEds5q.jpg",
        "The Amazing Spider-Man" to "/jexoNYnPd6vVrmygwF6QZmWPFdu.jpg",
        "The Avengers" to "/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
        "The Aviator" to "/lx4kWcZc3o9PaNxlQpEJZM17XUI.jpg",
        "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe" to "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
        "The Dark Knight" to "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        "The Dark Knight Rises" to "/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg",
        "The Departed" to "/nT97ifVT2J1yMQmeq20Qblg61T.jpg",
        "The Empire Strikes Back" to "/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg",
        "The Game" to "/zSqJ1qFq8NXFfi7JeIYMlzyR0dx.jpg",
        "The Godfather" to "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
        "The Great Gatsby" to "/nimh1rrDDLhgpG8XAYoUZXHYwb6.jpg",
        "The Green Mile" to "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
        "The Hateful Eight" to "/jIywvdPjia2t3eKYbjVTcwBQlG8.jpg",
        "The Hobbit: An Unexpected Journey" to "/yHA9Fc37VmpUA5UncTxxo3rTGVA.jpg",
        "The Hunger Games" to "/yXCbOiVDCxO71zI7cuwBRXdftq8.jpg",
        "The Hunger Games: Catching Fire" to "/vrQHDXjVmbYzadOXQ0UaObunoy2.jpg",
        "The Incredibles" to "/2LqaLgk4Z226KkgPJuiOQ58wvrm.jpg",
        "The Lion King" to "/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
        "The Little Mermaid" to "/plcZXvI310FkbwIptvd6rqk63LP.jpg",
        "The Lord of the Rings: The Fellowship of the Ring" to "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
        "The Martian" to "/fASz8A0yFE3QB6LgGoOfwvFSseV.jpg",
        "The Matrix" to "/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg",
        "The Maze Runner" to "/ode14q7WtDugFDp78fo9lCsmay9.jpg",
        "The Prestige" to "/Ag2B2KHKQPukjH7WutmgnnSNurZ.jpg",
        "The Shawshank Redemption" to "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
        "The Silence of the Lambs" to "/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
        "The Terminator" to "/qvktm0BHcnmDpul4Hz01GIazWPr.jpg",
        "The Thing" to "/tzGY49kseSE9QAKk47uuDGwnSCu.jpg",
        "The Wolf of Wall Street" to "/kW9LmvYHAaS9iA0tHmZVq8hQYoq.jpg",
        "Thor" to "/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg",
        "Titanic" to "/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
        "Total Recall" to "/wVbeL6fkbTKSmNfalj4VoAUUqJv.jpg",
        "Toy Story" to "/sfQtVlIHljToOwYjhe21KPGzZWK.jpg",
        "Transformers" to "/iRCgqpdVE4wyLQvGYU3ZP7pAtUc.jpg",
        "Troy" to "/a07wLy4ONfpsjnBqMwhlWTJTcm.jpg",
        "Up" to "/mFvoEwSfLqbcWwFsDjQebn9bzFe.jpg",
        "WALL·E" to "/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg",
        "X-Men" to "/ikA8UhYdTGpqbatFa93nIf6noSr.jpg",
        "X-Men: Days of Future Past" to "/tYfijzolzgoMOtegh1Y7j2Enorg.jpg",
        "Zodiac" to "/6YmeO4pB7XTh8P8F960O1uA14JO.jpg"
    )
}
